---

log:
  active_levels: # "info", "error", "fatal" - "all"; "all" specified as default
    - "all"
  output: "file" # "stdout" or "file", stdout specified as default
  path_to_file: # "all.log" specified as default
listen:
  bing_ip: 127.0.0.1
  port: ":8080"
storage:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
  sslmode: disable

