---

log:
  active_levels: # "info", "error", "fatal" - "all"
    - "all"
  output: "stdout" # "stdout" or "file"
  path_to_file:
listen:
  bing_ip: 127.0.0.1
  port: ":8080"
storage:
  host: localhost
  port: 5432
  database: postgres
  username: docker
  password: docker
  sslmode: disable

