version: "3.8"

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    restart: always
    volumes:
      - dbnews:/var/lib/docker/data
volumes:
  dbnews:
