version: "3.8"

services:
#  app:
 #   depends_on:
  #    - postgresql
   #   -

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - dbnews:/var/lib/docker/data
volumes:
  dbnews:
